# Generated by Django 3.0.2 on 2020-01-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtaCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_nm', models.CharField(max_length=100, verbose_name='인증서명')),
                ('pub_dt', models.DateField(verbose_name='유효기간시작일')),
                ('end_dt', models.DateField(verbose_name='유효기간종료일')),
                ('org_nm', models.CharField(max_length=20, verbose_name='인증기관')),
                ('oid', models.CharField(max_length=30, verbose_name='인증기관ID')),
                ('sn', models.CharField(max_length=20, verbose_name='시리얼넘버')),
                ('file1', models.CharField(max_length=1000, verbose_name='인증서')),
                ('file2', models.CharField(max_length=1000, verbose_name='개인키')),
                ('cert_pw', models.CharField(max_length=20, verbose_name='인증서비번')),
                ('num_used', models.IntegerField(blank=True, default=0, null=True, verbose_name='선택횟수')),
            ],
            options={
                'unique_together': {('cert_nm', 'end_dt')},
            },
        ),
        migrations.CreateModel(
            name='CtaIdPw',
            fields=[
                ('ctaid', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='세무대리인 ID')),
                ('pw', models.CharField(max_length=20, verbose_name='세무대리인 PW')),
                ('num_used', models.IntegerField(blank=True, default=0, null=True, verbose_name='선택횟수')),
                ('ctacert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nts.CtaCert')),
            ],
            options={
                'unique_together': {('ctacert', 'ctaid')},
            },
        ),
        migrations.CreateModel(
            name='BsIdPw',
            fields=[
                ('bsid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='사용자 ID')),
                ('pw', models.CharField(max_length=20, verbose_name='사용자 PW')),
                ('num_used', models.IntegerField(blank=True, default=0, null=True, verbose_name='선택횟수')),
                ('ctacert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nts.CtaCert')),
                ('ctaidpw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nts.CtaIdPw')),
            ],
            options={
                'unique_together': {('ctacert', 'ctaidpw', 'bsid')},
            },
        ),
    ]
